services:
  web:
    build: .
    volumes:
      - .:/app
    command: bash
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password